language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"


jobs:
    fast_finish: true
    allow_failures:
        - python: "2.7"
        - python: "3.4"
        - python: "3.5"
        - python: "3.8"

install:
    - python -m pip install -r requirements.txt
    - python -m pip install -e .
    
script: python tests